# Generated by Django 5.1.4 on 2025-02-18 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('logo_url', models.CharField(max_length=500)),
                ('details_url', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryDistribution',
            fields=[
                ('salary_range', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('student_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlacedStudent',
            fields=[
                ('student_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=255)),
                ('placement_year', models.IntegerField()),
                ('salary_lpa', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.company')),
            ],
        ),
    ]
