# Generated by Django 5.1.4 on 2025-03-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='details_url',
            field=models.URLField(blank=True, default='https://www.geeksforgeeks.org/companies/', null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo_url',
            field=models.CharField(default='Unknown Company', max_length=255),
        ),
    ]
