# Generated by Django 5.1.4 on 2025-03-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_alter_company_details_url_alter_company_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placedstudent',
            name='photo',
            field=models.ImageField(blank=True, default='achivers/Designer(1).png', null=True, upload_to='achievers/'),
        ),
    ]
