# Generated by Django 5.1.4 on 2025-03-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_alter_placedstudent_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placedstudent',
            name='photo',
            field=models.ImageField(blank=True, default='achievers/Designer_1.png', null=True, upload_to='achievers/'),
        ),
    ]
