# Generated by Django 5.1.4 on 2025-03-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_alter_placedstudent_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='placedstudent',
            name='branch',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
