# Generated by Django 5.1.4 on 2025-04-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0008_placedstudent_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='details_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo_url',
            field=models.CharField(max_length=255),
        ),
    ]
